name: Ronak Workflow

on: 
  push:

jobs:
    build: # jobs ka naam
        runs-on: ubuntu-latest  #github runner for free
        steps:
            - name: Checkout code
              uses: actions/checkout@v4   #clone the code into the ubuntu runner

            - name: setup docker
              uses: docker/setup-buildx-action@v4


